env:
  node: true
  es2021: true
extends: 'eslint:recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ['*.ejs']
rules: 
  no-console: off
  no-unused-vars: ['error', { 'vars': 'all', 'args': 'none' }]
  linebreak-style: ['error', 'windows']
  quotes: ['error', 'single']
  semi: ['error', 'always']
  no-trailing-spaces: ['error']
